version: '3.0'

services:
  react-app:
    image: react-app
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - api-estudiantes

  api-server:
    image: api-server
    ports:
      - "5000:5000"
    networks:
      - api-estudiantes
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - api-estudiantes
    volumes:
      - mongo-data:/data/db

networks:
  api-estudiantes:
    driver: bridge
